apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelico-tech-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelico-tech-test
  template:
    metadata:
      labels:
        app: pelico-tech-test
    spec:
      containers:
      - name: pelico-tech-test
        image: maeld/pelico-tech-test:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pelico-tech-test
spec:
  type: NodePort
  selector:
    app: pelico-tech-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

